services:
  unifi-controller:
    image: jacobalberty/unifi:latest
    container_name: unifi-controller
    restart: unless-stopped
    ports:
      - "3478:3478/udp"  # STUN
      - "10001:10001/udp" # Discovery
      - "8080:8080"       # Device/Controller Communication
      - "8443:8443"       # Web UI/API
      - "8843:8843"       # HTTPS Portal
      - "8880:8880"       # HTTP Portal
      - "6789:6789"       # Speed Test
    volumes:
      - ./data:/unifi/data
      - ./log:/unifi/log
      - ./cert:/unifi/cert
      - ./init.d:/unifi/init.d
    environment:
      - RUNAS_UID0=false
      - UNIFI_UID=1000
      - UNIFI_GID=1000
